# on branch main
# if find a tag, create a release
# linux
# then add mold
# just build for linux
name: 'Create release'

on: 
  push:
    branches: 
      - main
#    tags:
#      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: rui314/setup-mold@v1
      - run: sudo apt-get update
#      - run: sudo apt install libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev clang
      - run: > 
          sudo apt install libwebkit2gtk-4.0-dev
          build-essential
          libssl-dev
          libappindicator3-dev
          libappindicator3-1
          librsvg2-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v.0.0.1-alpha # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "test release"
          releaseBody: "testing asset uploads"
          releaseDraft: true
          prerelease: true 
